### ISSUE TITLE
QR scan for TLS Cert broken: writes integer into "Server Macaroon" field

### ISSUE THREAD

**Issue by Stadicus** [neogeno/shango-lightning-wallet#26]
- OS (Android/iOS)   **Android**
- Version of OS  **8.0.0**
- Device Make and Model   **Samsung Galaxy S9**
- Shango Version  **Alpha Testing Build 7**
- Device ID **d340382c5ed4bfb5**

## Expected Behavior
When connecting to my own LND backend, pressing the QR symbol for the TLS cert and scanning the QR code should fill the field "Server TLS Cert (Hex)".

## Current Behavior
I can no longer connect to my own LND node, as the QR scan of the Server TLS Cert does not work. Instead of filling the field "Server TLS Cert (Hex)", it puts an arbitrary number (like 18042926) into the "Server Macaroon" field. This number is different with every scan, the TLS field stays empty

On very rare occations, the TLS cert is read correctly and the right field is filled. But this happened only once today and I cannot reproduce it.

I used the following command to produce the QR code and the same installation / command worked before:  
`qrencode $(xxd -p -c2000 tls.cert) -t ANSIUTF8`

**Comment by neogeno** [comment]
Yes the delay is caused by the QR code library I am using and is more apparent on Android. You may have to tap or move closer or away from the code to gain focus first before it can recognise the QR code.

Since I cannot replicate your issue, can you try to delete the app, re-install and see if it helps?

**Comment by neogeno** [comment]
This should work now in build 18

**Comment by Stadicus** [comment]
Just reinstalled the Android App, it's still Alpha 7 and the error persists.
