### ISSUE TITLE
Can not enter more than 4 digits for opening a channel

### ISSUE THREAD

**Issue by frandani82** [neogeno/shango-lightning-wallet#49]
iOS
Version 12
Device iPhone X
Shango Version 1.07 , Build 35
Device ID: EEDC6AA9-614E-41BB-8563-A16AACE37D33

On iOS12, if I try to make a payment or invoice as soon as I enter the 5th digit it resets the field to empty.

Saw an issue with the same problem here but it should be fixed now. I have built 35 but still the same problem.

**Comment by neogeno** [comment]
@frandani82  can you tell me which locale/country/language you are using?

**Comment by frandani82** [comment]
country: Switzerland
language: english
currency: CHF

**Comment by neogeno** [comment]
I tried it with your Swiss settings and I can enter more than 4 digits in all fields. Can you record a video/screenshot and send it to me?

**Comment by frandani82** [comment]
yes, here you find the video

**Comment by neogeno** [comment]
Thank you it seems that it is the apostrophe " ' " character that is causing the issue with Shango. I have made a correction in the next build out today please try v1.08.2 and let me know. Thanks.

**Comment by frandani82** [comment]
Hi
tried it today with version 1.08.3 and have still the same behavier. After 4 digits the fiels resets.

**Comment by neogeno** [comment]
I removed the formatting it should work now

**Comment by frandani82** [comment]
Hi
Unfortunately the behaviour is still the same with the new version.
